### ISSUE TITLE
Fix swerve odometry

### ISSUE THREAD

**Issue by roterrex** [EMU4729/FRCTemplate#2]
the wheel steering optimiser can tell wheels to go to the target angle or target angle plus 180 degrees if that is closser.

this latter case needing the wheel to turn backwards is not handled by wheel odometry leading to incorrect distance traveled.

**Comment by oliverasi** [comment]
> Flipped swerve module position angle if wheel is turned backwarded.
> 
> Angle is flipped in getPosition() in SwerveModule
> 
> Untested

\- Noah
