### ISSUE TITLE
rework the function that optimizes the wheel steering direction

### ISSUE THREAD

**Issue by roterrex** [EMU4729/FRCTemplate#6]
This function optimizes per wheel steering so that each wheel will either steer to the target angle or target angle +180 whichever is closer.

the issue with this approach is that the optimisation can change suddenly when near 90deg from target. This changing results in sudden inversions in steering speed leading to extra wear on gears. 

The current patch on this system involves locking wheels into one option until either finished turning or a limit is reached. Limitations include, wheels chassing their tail when target angle changes at a similar rate to current angle, and wheels still snap changing when the limit is reached.

A better system should take current turn speed and current rate of change in target angle, and limit acceleration when changing optimisation to prevent snap changes.

**Comment by Rias296** [comment]
Made an algorithm that checks, and creates a 10 degrees threshold, to avoid snapping. Needs further testing for approval
