### ISSUE TITLE
add code to control acceleration of motors

### ISSUE THREAD

**Issue by roterrex** [EMU4729/FRCTemplate#7]
either per subsystem or as a utill function a system is needed to control how fast motors, mainly drive motors can accelerate and decelerate. 

Both swerve and tank codes along with general motors such as climb motors should not be instantly jumping from 0 to max or max to 0. This increases wear in gearboxes, wheels, and other moving parts.

a simple system is needed to limit accel and decel to take  at least a few tenths of seconds

**Comment by Rias296** [comment]
x axis is diffrence in velocity, use the function, as reference: 
![image](https://github.com/user-attachments/assets/4298ae7f-1cda-4fa9-b649-1a329995eb96)

**Comment by Rias296** [comment]
Use3 this instead as refernece: 
![image](https://github.com/user-attachments/assets/2d5fd31a-c358-4300-be2a-6623ca7802ff)
