### ISSUE TITLE
create tested code to handle motors controlled by run conditions

### ISSUE THREAD

**Issue by roterrex** [EMU4729/FRCTemplate#9]
we have at several points tried to make systems run to a limit switch or run only when condition is true. This has often ended in a motor either never running or worse able to lock on even when commands are no longer applied. 

we need either a system or tested example to handle motors that should only run while condition is true or keep running until conditions are false.

This must include a timeout plus other safetys, such as current limits, to prevent harm in case of error.

**Comment by Rias296** [comment]
Just need to test out code
